/*
 * nanopb Encode / Decode Demo
 * ----------------------------
 * Demonstrates the pattern for serializing and deserializing a Student
 * message using nanopb on an embedded system.
 *
 * To run this in a real project:
 *   1. pip install nanopb
 *   2. protoc --nanopb_out=. student.proto
 *   3. Add pb_encode.c, pb_decode.c, pb_common.c to your build
 *   4. Replace the hand-written struct below with: #include "student.pb.h"
 *
 * This file is self-contained for educational purposes — the struct and
 * field descriptors are written manually to show what nanopb normally
 * generates for you.
 */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>

/* -----------------------------------------------------------------------
 * In a real project these two lines replace everything in the
 * "HAND-WRITTEN NANOPB TYPES" section below:
 *
 *   #include <pb_encode.h>
 *   #include <pb_decode.h>
 *   #include "student.pb.h"
 * ----------------------------------------------------------------------- */

/* -----------------------------------------------------------------------
 * HAND-WRITTEN NANOPB TYPES
 * (Normally generated by: protoc --nanopb_out=. student.proto)
 * ----------------------------------------------------------------------- */

/* Matches the Department enum in student.proto */
typedef enum {
    Department_DEPARTMENT_UNKNOWN      = 0,
    Department_COMPUTER_SCIENCE        = 1,
    Department_ELECTRICAL_ENGINEERING  = 2,
    Department_MECHANICAL_ENGINEERING  = 3,
    Department_MATHEMATICS             = 4
} Department;

/*
 * Generated struct for the Student message.
 * String fields become fixed-size char arrays (from student.options).
 * repeated string courses → courses_count + courses[10][32]
 */
typedef struct {
    char       student_id[16];
    char       name[64];
    int32_t    age;
    Department department;
    uint8_t    courses_count;        /* how many entries are valid */
    char       courses[10][32];
    float      gpa;
    bool       is_enrolled;
} Student;

/* Zero-init macro (nanopb generates this as Student_init_zero) */
#define Student_init_zero { "", "", 0, Department_DEPARTMENT_UNKNOWN, 0, {""}, 0.0f, false }

/* -----------------------------------------------------------------------
 * MINIMAL PROTOBUF WIRE FORMAT ENCODER
 * (In a real project, pb_encode / pb_decode from nanopb handle this.)
 * This simplified encoder shows the concept: field_number + wire_type
 * tag prepended to each value.
 * ----------------------------------------------------------------------- */

#define WIRE_VARINT          0
#define WIRE_64BIT           1
#define WIRE_LENGTH_DELIMITED 2
#define WIRE_32BIT           5

#define MAKE_TAG(field_num, wire_type) (((field_num) << 3) | (wire_type))

static size_t encode_varint(uint8_t *buf, uint64_t value) {
    size_t i = 0;
    do {
        buf[i] = (uint8_t)(value & 0x7F);
        value >>= 7;
        if (value) buf[i] |= 0x80;
        i++;
    } while (value);
    return i;
}

static size_t encode_string(uint8_t *buf, uint8_t field_num, const char *str) {
    size_t len = strlen(str);
    size_t pos = 0;
    pos += encode_varint(buf + pos, MAKE_TAG(field_num, WIRE_LENGTH_DELIMITED));
    pos += encode_varint(buf + pos, (uint64_t)len);
    memcpy(buf + pos, str, len);
    pos += len;
    return pos;
}

static size_t encode_int32(uint8_t *buf, uint8_t field_num, int32_t value) {
    size_t pos = 0;
    pos += encode_varint(buf + pos, MAKE_TAG(field_num, WIRE_VARINT));
    pos += encode_varint(buf + pos, (uint64_t)(uint32_t)value);
    return pos;
}

static size_t encode_float(uint8_t *buf, uint8_t field_num, float value) {
    size_t pos = 0;
    pos += encode_varint(buf + pos, MAKE_TAG(field_num, WIRE_32BIT));
    memcpy(buf + pos, &value, 4);
    pos += 4;
    return pos;
}

static size_t encode_bool(uint8_t *buf, uint8_t field_num, bool value) {
    if (!value) return 0;   /* proto3: skip default (false) */
    size_t pos = 0;
    pos += encode_varint(buf + pos, MAKE_TAG(field_num, WIRE_VARINT));
    buf[pos++] = 1;
    return pos;
}

/*
 * Encode a Student into buf[].
 * Returns the number of bytes written.
 *
 * Field numbers match student.proto:
 *   1=student_id, 2=name, 3=age, 4=department, 5=courses, 6=gpa, 7=is_enrolled
 */
static size_t encode_student(uint8_t *buf, size_t buf_size, const Student *s) {
    size_t pos = 0;

    if (s->student_id[0])
        pos += encode_string(buf + pos, 1, s->student_id);

    if (s->name[0])
        pos += encode_string(buf + pos, 2, s->name);

    if (s->age != 0)
        pos += encode_int32(buf + pos, 3, s->age);

    if (s->department != Department_DEPARTMENT_UNKNOWN)
        pos += encode_int32(buf + pos, 4, (int32_t)s->department);

    for (int i = 0; i < s->courses_count; i++)
        pos += encode_string(buf + pos, 5, s->courses[i]);

    if (s->gpa != 0.0f)
        pos += encode_float(buf + pos, 6, s->gpa);

    pos += encode_bool(buf + pos, 7, s->is_enrolled);

    (void)buf_size;  /* would check overflow in production */
    return pos;
}

/* -----------------------------------------------------------------------
 * MINIMAL DECODER
 * ----------------------------------------------------------------------- */

static uint64_t decode_varint(const uint8_t *buf, size_t *pos) {
    uint64_t result = 0;
    int shift = 0;
    while (1) {
        uint8_t b = buf[(*pos)++];
        result |= (uint64_t)(b & 0x7F) << shift;
        if (!(b & 0x80)) break;
        shift += 7;
    }
    return result;
}

static void decode_student(const uint8_t *buf, size_t len, Student *s) {
    *s = (Student)Student_init_zero;
    size_t pos = 0;

    while (pos < len) {
        uint64_t tag    = decode_varint(buf, &pos);
        uint8_t  field  = (uint8_t)(tag >> 3);
        uint8_t  wtype  = (uint8_t)(tag & 0x07);

        if (wtype == WIRE_LENGTH_DELIMITED) {
            uint64_t slen = decode_varint(buf, &pos);
            switch (field) {
                case 1:  /* student_id */
                    memcpy(s->student_id, buf + pos,
                           slen < sizeof(s->student_id) - 1 ? slen : sizeof(s->student_id) - 1);
                    break;
                case 2:  /* name */
                    memcpy(s->name, buf + pos,
                           slen < sizeof(s->name) - 1 ? slen : sizeof(s->name) - 1);
                    break;
                case 5:  /* courses (repeated) */
                    if (s->courses_count < 10) {
                        size_t copy = slen < 31 ? slen : 31;
                        memcpy(s->courses[s->courses_count], buf + pos, copy);
                        s->courses[s->courses_count][copy] = '\0';
                        s->courses_count++;
                    }
                    break;
            }
            pos += (size_t)slen;
        } else if (wtype == WIRE_VARINT) {
            uint64_t val = decode_varint(buf, &pos);
            switch (field) {
                case 3: s->age        = (int32_t)val; break;
                case 4: s->department = (Department)val; break;
                case 7: s->is_enrolled = (bool)val; break;
            }
        } else if (wtype == WIRE_32BIT) {
            float val;
            memcpy(&val, buf + pos, 4);
            pos += 4;
            if (field == 6) s->gpa = val;
        } else if (wtype == WIRE_64BIT) {
            pos += 8;  /* skip unknown 64-bit fields */
        }
    }
}

/* -----------------------------------------------------------------------
 * HELPERS
 * ----------------------------------------------------------------------- */

static const char *department_name(Department d) {
    switch (d) {
        case Department_COMPUTER_SCIENCE:       return "Computer Science";
        case Department_ELECTRICAL_ENGINEERING: return "Electrical Engineering";
        case Department_MECHANICAL_ENGINEERING: return "Mechanical Engineering";
        case Department_MATHEMATICS:            return "Mathematics";
        default:                                return "Unknown";
    }
}

static void print_student(const Student *s) {
    printf("  Student ID : %s\n", s->student_id);
    printf("  Name       : %s\n", s->name);
    printf("  Age        : %d\n", s->age);
    printf("  Department : %s\n", department_name(s->department));
    printf("  GPA        : %.1f\n", s->gpa);
    printf("  Enrolled   : %s\n", s->is_enrolled ? "Yes" : "No");
    printf("  Courses (%d):\n", s->courses_count);
    for (int i = 0; i < s->courses_count; i++)
        printf("    - %s\n", s->courses[i]);
}

/* -----------------------------------------------------------------------
 * MAIN
 * ----------------------------------------------------------------------- */

int main(void) {
    printf("=== nanopb Encode/Decode Demo ===\n\n");

    /* 1. Build a Student */
    Student alice = Student_init_zero;
    strncpy(alice.student_id, "STU001", sizeof(alice.student_id) - 1);
    strncpy(alice.name,       "Alice",  sizeof(alice.name) - 1);
    alice.age        = 20;
    alice.department = Department_COMPUTER_SCIENCE;
    alice.gpa        = 3.8f;
    alice.is_enrolled = true;

    alice.courses_count = 2;
    strncpy(alice.courses[0], "Algorithms",  sizeof(alice.courses[0]) - 1);
    strncpy(alice.courses[1], "OS Design",   sizeof(alice.courses[1]) - 1);

    printf("[Original Student]\n");
    print_student(&alice);

    /* 2. Encode into buffer */
    /*
     * In a real nanopb project this would be:
     *   pb_ostream_t stream = pb_ostream_from_buffer(buffer, sizeof(buffer));
     *   pb_encode(&stream, Student_fields, &alice);
     *   size_t encoded_size = stream.bytes_written;
     */
    static uint8_t buffer[256];
    memset(buffer, 0, sizeof(buffer));
    size_t encoded_size = encode_student(buffer, sizeof(buffer), &alice);

    printf("\n[Encoded — %zu bytes]\n", encoded_size);
    printf("Hex: ");
    for (size_t i = 0; i < encoded_size; i++) printf("%02X ", buffer[i]);
    printf("\n");
    printf("(Equivalent JSON would be ~90 bytes)\n");

    /* 3. Simulate transmit: buffer[0..encoded_size-1] goes over UART/BLE/flash */

    /* 4. Decode back */
    /*
     * In a real nanopb project this would be:
     *   pb_istream_t stream = pb_istream_from_buffer(buffer, encoded_size);
     *   Student decoded = Student_init_zero;
     *   pb_decode(&stream, Student_fields, &decoded);
     */
    Student decoded = Student_init_zero;
    decode_student(buffer, encoded_size, &decoded);

    printf("\n[Decoded Student]\n");
    print_student(&decoded);

    /* 5. Verify round-trip */
    bool match = (strcmp(alice.student_id, decoded.student_id) == 0) &&
                 (strcmp(alice.name,       decoded.name)       == 0) &&
                 (alice.age        == decoded.age)                    &&
                 (alice.department == decoded.department)             &&
                 (alice.is_enrolled == decoded.is_enrolled);

    printf("\nRound-trip check: %s\n", match ? "PASS" : "FAIL");
    return match ? 0 : 1;
}
